### ISSUE TITLE
How to extract Telephone Number

### ISSUE THREAD

**Issue by jersonjunior** [danielcardeenas/whatsapp-framework#187]
Is posible to extract Telephone number?
Example:
number = "5218114140740@s.whatsapp.net" # Daniel Cardenas

Or only 5218114140740

**Comment by ffcc** [comment]
Hi @jersonjunior 

What do you mean with "extract"? Do you need that given a whatsapp id 5218114140740@s.whatsapp.net get only the number? Is that so you only need to split the id and get the number. Example:
```
def get_number(id):
    return id.split("@")[0]
```

**Comment by jersonjunior** [comment]
I need to know the number:

def hi(message):
    telephone = message.What?
    print (telephone)
    who_name = message.who
    answer = "Hi " + who_name
    mac.send_message(answer, message.conversation)

**Comment by ffcc** [comment]
Ok, you need to use the message.who attribute that is the whatsapp ID of the contact. The ID always would contain the number because for whatsapp the complete number (country code + number) is an unique identifier.

To get the name you need to use the message.who_name attribute.

Following your example it would look like follows:

```
def hi(message):
    telephone = message.who.split("@")[0]
    print(telephone)
    who_name = message.who_name
    answer = "Hi " + who_name
    mac.send_message(answer, message.conversation)
```

**Comment by jersonjunior** [comment]
Thanks works fine with this example!
