### ISSUE TITLE
Can I have the bot running in Debian and at the same time have the whatsapp open with the same number in my cell phone?

### ISSUE THREAD

**Issue by rgchurion** [danielcardeenas/whatsapp-framework#215]
Maybe my question is silly and I might know the answer, but I would like to confirm it: I can have the bot running on the Debian server and at the same time have the whatsapp session open with that same number on a cell phone? both at the time? In case you can not, could you "turn off" the bot and open the session on a cell phone so that both are not open at the same time?

**Comment by superlandero** [comment]
I tried that, but WhatsApp only allows you to have the session open on a single device. First I entered from the mobile, then from the server and the mobile session was closed and I needed the whatsapp confirmation code. By the way, you can not enter and exit the session because whatsapp puts you on hold for a new confirmation code.

As I said, that has been my experience in this regard.

**Comment by rgchurion** [comment]
@superlandero Thanks you very much!!
